name: Integración Continua

on:
  push:
    paths-ignore:
      - '!*.md'
  pull_request:
    paths-ignore:
      - '!*.md'

jobs:
  unittest:
    name: Ejecución de Pruebas
    runs-on: ubuntu-18.04
    container:
      image: python:3.7
      env:
        DJANGO_SETTINGS_MODULE: config.settings.ci
    steps:
      - uses: actions/checkout@v2
      - name: Instalando dependencias
        run: pip install -r requirements/ci.txt
      - name: Corriento pruebas
        run: make test
